In [1]:
import os

print("Current working directory:", os.getcwd())
print("Files in current directory:", os.listdir())

Current working directory: /home/s2026ak05477/workspace/Ml_Assignment_2
Files in current directory: ['.ipynb_checkpoints', 'bank.csv', 'ML_Assignment2_Bank_Marketing.ipynb']

In [1]:
import pandas as pd

# Load the Bank Marketing dataset
df = pd.read_csv("bank.csv", sep=";")

# Display basic information
print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

# Display the first five rows
display(df.head())

Dataset loaded successfully!
Number of rows: 4521
Number of columns: 17

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [3]:
# Display all column names
print("Column Names:")
print(df.columns.tolist())

# Display data types and non-null counts
print("\nDataset Information:")
df.info()

Column Names:
['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

In [5]:
# Count missing values in each column
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [7]:
# Count duplicate rows
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [9]:
# Count customers in each target class
print("Target Variable Distribution:")
print(df["y"].value_counts())

# Display class proportions
print("\nTarget Variable Percentages:")
print((df["y"].value_counts(normalize=True) * 100).round(2))

Target Variable Distribution:
y
no     4000
yes     521
Name: count, dtype: int64

Target Variable Percentages:
y
no     88.48
yes    11.52
Name: proportion, dtype: float64

In [11]:
print("Dataset shape:", df.shape)
print("\nTarget counts:")
print(df["y"].value_counts(dropna=False))

print("\nTarget percentages:")
print((df["y"].value_counts(normalize=True, dropna=False) * 100).round(2))

Dataset shape: (4521, 17)

Target counts:
y
no     4000
yes     521
Name: count, dtype: int64

Target percentages:
y
no     88.48
yes    11.52
Name: proportion, dtype: float64

In [13]:
import pandas as pd

df_check = pd.read_csv("bank.csv", sep=";")

print("Rows in CSV:", len(df_check))
print("Columns in CSV:", len(df_check.columns))
print("Target counts in CSV:")
print(df_check["y"].value_counts(dropna=False))

Rows in CSV: 4521
Columns in CSV: 17
Target counts in CSV:
y
no     4000
yes     521
Name: count, dtype: int64

In [15]:
# Identify numerical and categorical columns

numerical_cols = df.select_dtypes(include=["number"]).columns.tolist()
categorical_cols = df.select_dtypes(exclude=["number"]).columns.tolist()

print("Numerical columns:")
print(numerical_cols)

print("\nCategorical columns:")
print(categorical_cols)

print("\nNumber of numerical columns:", len(numerical_cols))
print("Number of categorical columns:", len(categorical_cols))

Numerical columns:
['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

Categorical columns:
['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']

Number of numerical columns: 7
Number of categorical columns: 10

In [17]:
# Statistical summary of numerical columns

display(df.describe())

,age,balance,day,duration,campaign,pdays,previous
count,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000
mean,41.170095,1422.657819,15.915284,263.961292,2.793630,39.766645,0.542579
std,10.576211,3009.638142,8.247667,259.856633,3.109807,100.121124,1.693562
min,19.000000,-3313.000000,1.000000,4.000000,1.000000,-1.000000,0.000000
25%,33.000000,69.000000,9.000000,104.000000,1.000000,-1.000000,0.000000
50%,39.000000,444.000000,16.000000,185.000000,2.000000,-1.000000,0.000000
75%,49.000000,1480.000000,21.000000,329.000000,3.000000,-1.000000,0.000000
max,87.000000,71188.000000,31.000000,3025.000000,50.000000,871.000000,25.000000

In [19]:
# Inspect unique values in categorical columns

for col in categorical_cols:
    print(f"\n{col}:")
    print(df[col].value_counts().head(10))

job:
job
management       969
blue-collar      946
technician       768
admin.           478
services         417
retired          230
self-employed    183
entrepreneur     168
unemployed       128
housemaid        112
Name: count, dtype: int64

marital:
marital
married     2797
single      1196
divorced     528
Name: count, dtype: int64

education:
education
secondary    2306
tertiary     1350
primary       678
unknown       187
Name: count, dtype: int64

default:
default
no     4445
yes      76
Name: count, dtype: int64

housing:
housing
yes    2559
no     1962
Name: count, dtype: int64

loan:
loan
no     3830
yes     691
Name: count, dtype: int64

contact:
contact
cellular     2896
unknown      1324
telephone     301
Name: count, dtype: int64

month:
month
may    1398
jul     706
aug     633
jun     531
nov     389
apr     293
feb     222
jan     148
oct      80
sep      52
Name: count, dtype: int64

poutcome:
poutcome
unknown    3705
failure     490
other       197
success     129
Name: count, dtype: int64

y:
y
no     4000
yes     521
Name: count, dtype: int64

In [1]:
import numpy as np
import scipy
import sklearn

print("NumPy:", np.__version__)
print("SciPy:", scipy.__version__)
print("Scikit-learn:", sklearn.__version__)
print("All imports successful!")

NumPy: 2.2.6
SciPy: 1.15.3
Scikit-learn: 1.6.1
All imports successful!

In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("bank.csv", sep=";")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)
print("\nFirst five rows:")
display(df.head())

print("\nTarget distribution:")
print(df["y"].value_counts())

Dataset loaded successfully!
Dataset shape: (4521, 17)

First five rows:

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

Target distribution:
y
no     4000
yes     521
Name: count, dtype: int64

In [7]:
# Import required libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef
)

# Prepare features and target
X = df.drop(columns=["y"])
y = df["y"].map({"no": 0, "yes": 1})

# Identify numerical and categorical columns
numerical_cols = X.select_dtypes(include=["number"]).columns.tolist()
categorical_cols = X.select_dtypes(exclude=["number"]).columns.tolist()

print("Number of input features:", X.shape[1])
print("Numerical features:", len(numerical_cols))
print("Categorical features:", len(categorical_cols))

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))

# Preprocess numerical and categorical features
preprocessor = ColumnTransformer(
    transformers=[
        ("numerical", StandardScaler(), numerical_cols),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            categorical_cols
        )
    ]
)

# Define the five classification models
models = {
    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=42
    ),

    "Decision Tree": DecisionTreeClassifier(
        random_state=42
    ),

    "KNN": KNeighborsClassifier(
        n_neighbors=5
    ),

    "Naive Bayes": GaussianNB(),

    "Support Vector Machine": SVC(
        probability=True,
        random_state=42
    )
}

# Train and evaluate all models
results = []
trained_models = {}

for model_name, classifier in models.items():

    print("\nTraining:", model_name)

    model_pipeline = Pipeline(
        steps=[
            ("preprocessing", preprocessor),
            ("classifier", classifier)
        ]
    )

    model_pipeline.fit(X_train, y_train)

    # Generate predictions
    y_pred = model_pipeline.predict(X_test)
    y_prob = model_pipeline.predict_proba(X_test)[:, 1]

    # Calculate evaluation metrics
    metrics = {
        "Model": model_name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "AUC": roc_auc_score(y_test, y_prob),
        "Precision": precision_score(
            y_test, y_pred, zero_division=0
        ),
        "Recall": recall_score(
            y_test, y_pred, zero_division=0
        ),
        "F1 Score": f1_score(
            y_test, y_pred, zero_division=0
        ),
        "MCC": matthews_corrcoef(y_test, y_pred)
    }

    results.append(metrics)
    trained_models[model_name] = model_pipeline

    print("Completed:", model_name)

# Display the model comparison table
results_df = pd.DataFrame(results)

print("\nMODEL PERFORMANCE COMPARISON")
display(results_df.round(4))

Number of input features: 16
Numerical features: 7
Categorical features: 9

Training samples: 3616
Testing samples: 905

Training: Logistic Regression
Completed: Logistic Regression

Training: Decision Tree
Completed: Decision Tree

Training: KNN
Completed: KNN

Training: Naive Bayes
Completed: Naive Bayes

Training: Support Vector Machine
Completed: Support Vector Machine

MODEL PERFORMANCE COMPARISON

,Model,Accuracy,AUC,Precision,Recall,F1 Score,MCC
0,Logistic Regression,0.8928,0.8913,0.5636,0.2981,0.3899,0.3579
1,Decision Tree,0.8586,0.6942,0.4032,0.4808,0.4386,0.3602
2,KNN,0.8840,0.7692,0.4872,0.1827,0.2657,0.2477
3,Naive Bayes,0.8210,0.7881,0.3092,0.4519,0.3672,0.2737
4,Support Vector Machine,0.8939,0.8830,0.5909,0.2500,0.3514,0.3374

In [9]:
import os
import joblib

# Create a folder to store the trained models
os.makedirs("model", exist_ok=True)

# Save all five trained models
for model_name, model_pipeline in trained_models.items():
    filename = (
        model_name.lower()
        .replace(" ", "_")
        + ".joblib"
    )

    filepath = os.path.join("model", filename)

    joblib.dump(model_pipeline, filepath)

    print("Saved:", filepath)

print("\nAll models saved successfully!")

Saved: model/logistic_regression.joblib
Saved: model/decision_tree.joblib
Saved: model/knn.joblib
Saved: model/naive_bayes.joblib
Saved: model/support_vector_machine.joblib

All models saved successfully!

In [11]:
import os
import joblib

model_folder = "model"

print("VERIFYING SAVED MODELS\n")

for filename in sorted(os.listdir(model_folder)):
    if filename.endswith(".joblib"):
        filepath = os.path.join(model_folder, filename)

        try:
            loaded_model = joblib.load(filepath)
            print(f"SUCCESS: {filename} loaded correctly")
        except Exception as e:
            print(f"ERROR: {filename} - {e}")

print("\nVerification completed.")

VERIFYING SAVED MODELS

SUCCESS: decision_tree.joblib loaded correctly
SUCCESS: knn.joblib loaded correctly
SUCCESS: logistic_regression.joblib loaded correctly
SUCCESS: naive_bayes.joblib loaded correctly
SUCCESS: support_vector_machine.joblib loaded correctly

Verification completed.

In [13]:
import os
import pandas as pd

# Check that the existing test data is available
print("Checking existing test dataset...")

try:
    print("Test features shape:", X_test.shape)
    print("Test target shape:", y_test.shape)

    # Combine test features and target
    test_data = X_test.copy()

    # Preserve the original target labels
    test_data["y"] = y_test.values

    # Save the test dataset
    test_data.to_csv("test_data.csv", index=False)

    print("\nTest dataset saved successfully!")
    print("File: test_data.csv")
    print("Dataset shape:", test_data.shape)
    print("\nFirst five rows:")
    display(test_data.head())

except NameError as e:
    print("Required test data variable not found:", e)
    print("We will locate the correct variables before proceeding.")

Checking existing test dataset...
Test features shape: (905, 16)
Test target shape: (905,)

Test dataset saved successfully!
File: test_data.csv
Dataset shape: (905, 17)

First five rows:

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
2032,59,management,married,primary,no,1727,no,no,telephone,25,may,500,4,358,2,failure,1
943,40,technician,married,secondary,no,109,no,no,unknown,20,jun,402,22,-1,0,unknown,0
408,44,management,married,secondary,no,438,yes,no,telephone,8,may,37,3,303,1,failure,0
3034,29,services,married,primary,no,-102,no,no,unknown,4,jul,134,1,-1,0,unknown,0
3447,53,management,married,tertiary,no,146,no,no,unknown,30,may,150,1,-1,0,unknown,0

In [15]:
import os

print("CURRENT WORKING DIRECTORY:")
print(os.getcwd())

print("\nFILES AND FOLDERS:")
for item in sorted(os.listdir(".")):
    if os.path.isdir(item):
        print(f"[FOLDER] {item}/")
    else:
        print(f"[FILE]   {item}")

print("\nSAVED MODEL FILES:")
model_folder = "model"

if os.path.exists(model_folder):
    for filename in sorted(os.listdir(model_folder)):
        print(filename)
else:
    print("Model folder not found.")

CURRENT WORKING DIRECTORY:
/home/s2026ak05477/workspace/Ml_Assignment_2

FILES AND FOLDERS:
[FOLDER] .ipynb_checkpoints/
[FILE]   ML_Assignment2_Bank_Marketing.ipynb
[FILE]   bank.csv
[FOLDER] model/
[FILE]   test_data.csv

SAVED MODEL FILES:
decision_tree.joblib
knn.joblib
logistic_regression.joblib
naive_bayes.joblib
support_vector_machine.joblib

In [17]:
import os

print("PROJECT FILES")
print("-" * 40)

for root, dirs, files in os.walk("."):
    dirs[:] = [d for d in dirs if d != ".ipynb_checkpoints"]

    for file in files:
        print(os.path.join(root, file))

PROJECT FILES
----------------------------------------
./bank.csv
./test_data.csv
./ML_Assignment2_Bank_Marketing.ipynb
./model/naive_bayes.joblib
./model/logistic_regression.joblib
./model/decision_tree.joblib
./model/support_vector_machine.joblib
./model/knn.joblib